In [1]:
import pandas as pd
import numpy as np

In [2]:
X=pd.read_csv("train.csv")
X_train=X.iloc[:,:-1]
y_train=X.iloc[:,-1:]

In [3]:
y=pd.read_csv("test.csv")
X_test=y.iloc[:,:-1]
y_test=y.iloc[:,-1:]

In [4]:
X_train.shape

(103904, 24)

In [5]:
X_test.shape

(25976, 24)

In [6]:
y_train.shape

(103904, 1)

In [7]:
y_test

satisfaction
0                    satisfied
1                    satisfied
2      neutral or dissatisfied
3                    satisfied
4                    satisfied
...                        ...
25971  neutral or dissatisfied
25972                satisfied
25973  neutral or dissatisfied
25974                satisfied
25975  neutral or dissatisfied

[25976 rows x 1 columns]

In [8]:
y_test = pd.get_dummies(y_test)
y_test=y_test['satisfaction_satisfied']
#y_test=pd.DataFrame(y_test)
y_test

0        1
1        1
2        0
3        1
4        1
        ..
25971    0
25972    1
25973    0
25974    1
25975    0
Name: satisfaction_satisfied, Length: 25976, dtype: uint8

In [9]:
y_train = pd.get_dummies(y_train)
y_train=y_train['satisfaction_satisfied']
#y_train=pd.DataFrame(y_train)
y_train

0         0
1         0
2         1
3         0
4         1
         ..
103899    0
103900    1
103901    0
103902    0
103903    0
Name: satisfaction_satisfied, Length: 103904, dtype: uint8

In [10]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.metrics import accuracy_score

In [11]:
X_train=X_train.drop(["Type of Travel","Class","Gender","id","Unnamed: 0"],axis=1)
X_ones=pd.get_dummies(X_train["Customer Type"])["Loyal Customer"]
X_train=pd.concat((X_ones,X_train),axis=1)
X_train=X_train.drop(["Customer Type"],axis=1)
X_train.fillna(X_train.mean(),inplace=True)
X_train

Loyal Customer  Age  Flight Distance  Inflight wifi service  \
0                    1   13              460                      3   
1                    0   25              235                      3   
2                    1   26             1142                      2   
3                    1   25              562                      2   
4                    1   61              214                      3   
...                ...  ...              ...                    ...   
103899               0   23              192                      2   
103900               1   49             2347                      4   
103901               0   30             1995                      1   
103902               0   22             1000                      1   
103903               1   27             1723                      1   

        Departure/Arrival time convenient  Ease of Online booking  \
0                                       4                       3   
1                                       2                       3   
2                                       2                       2   
3                                       5                       5   
4                                       3                       3   
...                                   ...                     ...   
103899                                  1                       2   
103900                                  4                       4   
103901                                  1                       1   
103902                                  1                       1   
103903                                  3                       3   

        Gate location  Food and drink  Online boarding  Seat comfort  \
0                   1               5                3             5   
1                   3               1                3             1   
2                   2               5                5             5   
3                   5               2                2             2   
4                   3               4                5             5   
...               ...             ...              ...           ...   
103899              3               2                2             2   
103900              4               2                4             5   
103901              3               4                1             5   
103902              5               1                1             1   
103903              3               1                1             1   

        Inflight entertainment  On-board service  Leg room service  \
0                            5                 4                 3   
1                            1                 1                 5   
2                            5                 4                 3   
3                            2                 2                 5   
4                            3                 3                 4   
...                        ...               ...               ...   
103899                       2                 3                 1   
103900                       5                 5                 5   
103901                       4                 3                 2   
103902                       1                 4                 5   
103903                       1                 1                 1   

        Baggage handling  Checkin service  Inflight service  Cleanliness  \
0                      4                4                 5            5   
1                      3                1                 4            1   
2                      4                4                 4            5   
3                      3                1                 4            2   
4                      4                3                 3            3   
...                  ...              ...               ...          ...   
103899                 4                2                 3            2   
103900      

In [12]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_train

array([[1.00000000e+00, 7.69230769e-02, 8.66316640e-02, ...,
        1.00000000e+00, 1.57035176e-02, 1.13636364e-02],
       [0.00000000e+00, 2.30769231e-01, 4.11954766e-02, ...,
        2.00000000e-01, 6.28140704e-04, 3.78787879e-03],
       [1.00000000e+00, 2.43589744e-01, 2.24353796e-01, ...,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [0.00000000e+00, 2.94871795e-01, 3.96607431e-01, ...,
        8.00000000e-01, 4.39698492e-03, 8.83838384e-03],
       [0.00000000e+00, 1.92307692e-01, 1.95678514e-01, ...,
        2.00000000e-01, 0.00000000e+00, 0.00000000e+00],
       [1.00000000e+00, 2.56410256e-01, 3.41680129e-01, ...,
        2.00000000e-01, 0.00000000e+00, 0.00000000e+00]])

In [13]:
X_test

Unnamed: 0     id  Gender      Customer Type  Age   Type of Travel  \
0               0  19556  Female     Loyal Customer   52  Business travel   
1               1  90035  Female     Loyal Customer   36  Business travel   
2               2  12360    Male  disloyal Customer   20  Business travel   
3               3  77959    Male     Loyal Customer   44  Business travel   
4               4  36875  Female     Loyal Customer   49  Business travel   
...           ...    ...     ...                ...  ...              ...   
25971       25971  78463    Male  disloyal Customer   34  Business travel   
25972       25972  71167    Male     Loyal Customer   23  Business travel   
25973       25973  37675  Female     Loyal Customer   17  Personal Travel   
25974       25974  90086    Male     Loyal Customer   14  Business travel   
25975       25975  34799  Female     Loyal Customer   42  Personal Travel   

          Class  Flight Distance  Inflight wifi service  \
0           Eco              160                      5   
1      Business             2863                      1   
2           Eco              192                      2   
3      Business             3377                      0   
4           Eco             1182                      2   
...         ...              ...                    ...   
25971  Business              526                      3   
25972  Business              646                      4   
25973       Eco              828                      2   
25974  Business             1127                      3   
25975       Eco              264                      2   

       Departure/Arrival time convenient  ...  Seat comfort  \
0                                      4  ...             3   
1                                      1  ...             5   
2                                      0  ...             2   
3                                      0  ...             4   
4                                      3  ...             2   
...                                  ...  ...           ...   
25971                                  3  ...             4   
25972                                  4  ...             4   
25973                                  5  ...             2   
25974                                  3  ...             4   
25975                                  5  ...             2   

       Inflight entertainment  On-board service  Leg room service  \
0                           5                 5                 5   
1                           4                 4                 4   
2                           2                 4                 1   
3                           1                 1                 1   
4                           2                 2                 2   
...                       ...               ...               ...   
25971                       4                 3                 2   
25972                       4                 4                 5   
25973                       2                 4                 3   
25974                       4                 3                 2   
25975                       1                 1                 2   

       Baggage handling  Checkin service  Inflight service  Cleanliness  \
0                     5                2                 5            5   
1                     4                3                 4            5   
2                     3                2                 2            2   
3                     1                3                 1            4   
4                     2                4                 2            4   
...                 ...              ...               ...          ...   
25971                 4                4                 5            4   
25972                 5                5                 5            4   
25973                 4                5                 4            2   
25974                 5              

In [14]:
X_test=X_test.drop(["Type of Travel","Class","Gender","id","Unnamed: 0"],axis=1)
X_ones=pd.get_dummies(X_test["Customer Type"])["Loyal Customer"]
X_test=pd.concat((X_ones,X_test),axis=1)
X_test=X_test.drop(["Customer Type"],axis=1)
X_test.fillna(X_test.mean(),inplace=True)
X_test

Loyal Customer  Age  Flight Distance  Inflight wifi service  \
0                   1   52              160                      5   
1                   1   36             2863                      1   
2                   0   20              192                      2   
3                   1   44             3377                      0   
4                   1   49             1182                      2   
...               ...  ...              ...                    ...   
25971               0   34              526                      3   
25972               1   23              646                      4   
25973               1   17              828                      2   
25974               1   14             1127                      3   
25975               1   42              264                      2   

       Departure/Arrival time convenient  Ease of Online booking  \
0                                      4                       3   
1                                      1                       3   
2                                      0                       2   
3                                      0                       0   
4                                      3                       4   
...                                  ...                     ...   
25971                                  3                       3   
25972                                  4                       4   
25973                                  5                       1   
25974                                  3                       3   
25975                                  5                       2   

       Gate location  Food and drink  Online boarding  Seat comfort  \
0                  4               3                4             3   
1                  1               5                4             5   
2                  4               2                2             2   
3                  2               3                4             4   
4                  3               4                1             2   
...              ...             ...              ...           ...   
25971              1               4                3             4   
25972              4               4                4             4   
25973              5               2                1             2   
25974              3               4                4             4   
25975              5               4                2             2   

       Inflight entertainment  On-board service  Leg room service  \
0                           5                 5                 5   
1                           4                 4                 4   
2                           2                 4                 1   
3                           1                 1                 1   
4                           2                 2                 2   
...                       ...               ...               ...   
25971                       4                 3                 2   
25972                       4                 4                 5   
25973                       2                 4                 3   
25974                       4                 3                 2   
25975                       1                 1                 2   

       Baggage handling  Checkin service  Inflight service  Cleanliness  \
0                     5                2                 5            5   
1                     4                3                 4            5   
2                     3                2                 2            2   
3                     1                3                 1            4   
4                     2                4                 2            4   
...                 ...              ...               ...          ...   
25971                 4                4                 5            4   
25972                 5                5                 5         

In [15]:
X_test = scaler.transform(X_test)
X_test

array([[1.        , 0.57692308, 0.02605008, ..., 1.        , 0.03140704,
        0.02777778],
       [1.        , 0.37179487, 0.57189015, ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.16666667, 0.03251212, ..., 0.4       , 0.        ,
        0.        ],
       ...,
       [1.        , 0.12820513, 0.16094507, ..., 0.4       , 0.        ,
        0.        ],
       [1.        , 0.08974359, 0.22132472, ..., 0.8       , 0.        ,
        0.        ],
       [1.        , 0.44871795, 0.0470517 , ..., 0.2       , 0.        ,
        0.        ]])

In [16]:
y_test

0        1
1        1
2        0
3        1
4        1
        ..
25971    0
25972    1
25973    0
25974    1
25975    0
Name: satisfaction_satisfied, Length: 25976, dtype: uint8

In [17]:
X_test

array([[1.        , 0.57692308, 0.02605008, ..., 1.        , 0.03140704,
        0.02777778],
       [1.        , 0.37179487, 0.57189015, ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.16666667, 0.03251212, ..., 0.4       , 0.        ,
        0.        ],
       ...,
       [1.        , 0.12820513, 0.16094507, ..., 0.4       , 0.        ,
        0.        ],
       [1.        , 0.08974359, 0.22132472, ..., 0.8       , 0.        ,
        0.        ],
       [1.        , 0.44871795, 0.0470517 , ..., 0.2       , 0.        ,
        0.        ]])

In [18]:
model=Sequential()
model.add(tf.keras.layers.Dense(units=10,activation='relu',input_dim=len(X_train[0])))
model.add(tf.keras.layers.Dense(units=10,activation='relu'))
model.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))


In [19]:
from tensorflow.keras.optimizers import Adagrad
cust=Adagrad(learning_rate=0.1)
model.compile(loss='binary_crossentropy',optimizer=cust ,metrics=['accuracy'])

In [20]:
model.fit(X_train, y_train, epochs=100, batch_size=600)

Epoch 1/100
174/174 [==============================] - 1s 2ms/step - loss: 0.4852 - accuracy: 0.7828
Epoch 2/100
174/174 [==============================] - 0s 2ms/step - loss: 0.3786 - accuracy: 0.8441
Epoch 3/100
174/174 [==============================] - 0s 2ms/step - loss: 0.3318 - accuracy: 0.8615
Epoch 4/100
174/174 [==============================] - 0s 2ms/step - loss: 0.3001 - accuracy: 0.8728
Epoch 5/100
174/174 [==============================] - 0s 2ms/step - loss: 0.2828 - accuracy: 0.8793
Epoch 6/100
174/174 [==============================] - 0s 2ms/step - loss: 0.2739 - accuracy: 0.8835
Epoch 7/100
174/174 [==============================] - 0s 2ms/step - loss: 0.2658 - accuracy: 0.8871
Epoch 8/100
174/174 [==============================] - 0s 3ms/step - loss: 0.2593 - accuracy: 0.8896
Epoch 9/100
174/174 [==============================] - 0s 3ms/step - loss: 0.2535 - accuracy: 0.8924
Epoch 10/100
174/174 [==============================] - 0s 3ms/step - loss: 0.2489 - accura

In [21]:
y_pred=model.predict(X_test)
y_pred= [0 if val<0.5 else 1 for val in y_pred]


812/812 [==============================] - 1s 1ms/step


In [22]:
accuracy_score(y_test,y_pred)

0.9330535879273175

In [23]:
#Using my randomly generated feedback data
p=np.array([1,19,3350,5,4,5,4,5,5,5,5,4,4,5,4,5,5,5,7.0])
p=p.reshape(1,-1)
p=scaler.transform(p)
y_prede=model.predict(p)
y_prede

1/1 [==============================] - 0s 22ms/step


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


array([[0.9967319]], dtype=float32)

In [24]:
if y_prede>=0.5:
  print("satisfied")
else:
  print("not satisfied")

satisfied
